all: vencrypt vdecrypt scrypt sbencrypt sbdecrypt

vencrypt:
	gcc -o vencrypt vencrypt.c

vdecrypt:
	gcc -o vdecrypt vdecrypt.c

scrypt:
	gcc -o scrypt scrypt.c

sbencrypt:
	gcc -o sbencrypt sbencrypt.c

sbdecrypt:
	gcc -o sbdecrypt sbdecrypt.c

clean:
	rm -f vencrypt vdecrypt scrypt sbencrypt sbdecrypt *.o
